### ISSUE TITLE
测试用例报错

### ISSUE THREAD

**Issue by karott** [blockchain-jd-com/jdchain-starter#2]
运行jdchain-starter测试用例均报如下错误(jdchain已经正常启动且均能正常访问)：

![image](https://user-images.githubusercontent.com/3212080/56290119-0a093200-6155-11e9-83cf-956b7cbe8a53.png)

麻烦指点下 谢谢！

**Comment by zhaoGuangwei** [comment]
先看看最新版中的文件“常见问题.md”中的第一个问题，看看能不能解决。愉快！

**Comment by karott** [comment]
我看了，我目前还没到合约部分  就是执行常规部分用例报这个错呢，与问题列表1不太一样

**Comment by zhaoGuangwei** [comment]
好的，我已经将您的实践写入master的“常见问题.md”中的：1.2 场景2，感谢您的参与，愉快！

**Comment by jy1989** [comment]
> 找到问题了，是配置文件里面的ledgerhash与链里面的不一样

请问是哪个配置文件的ledgerhash？
