### ISSUE TITLE
prepTx.commit() 报错：java.lang.IllegalStateException: Returned object not currently part of this pool

### ISSUE THREAD

**Issue by jy1989** [blockchain-jd-com/jdchain-starter#5]
gateway正常：
![image](https://user-images.githubusercontent.com/1291756/68186625-883d0100-ffdf-11e9-8e51-0854a11a49df.png)
地址配置应该也正确
![image](https://user-images.githubusercontent.com/1291756/68187558-f256a580-ffe1-11e9-9f60-e0af18e7bba3.png)

但执行commit就报错了：

![image](https://user-images.githubusercontent.com/1291756/68187649-27fb8e80-ffe2-11e9-8b32-c7394e8cc1ec.png)

**Comment by jy1989** [comment]
gateway 报错 看上去好像是redis的问题

![image](https://user-images.githubusercontent.com/1291756/68266262-87f94000-0089-11ea-91ab-1775232c79c9.png)

**Comment by jy1989** [comment]
才发现工具配置是不支持redis的

![image](https://user-images.githubusercontent.com/1291756/68272714-7327a700-009f-11ea-8315-398c534db3a3.png)

会生成
![image](https://user-images.githubusercontent.com/1291756/68272844-d3b6e400-009f-11ea-8580-e2bc89150e14.png)

**Comment by zhaoGuangwei** [comment]
这个报错，是由于连接意外中断导致的。你可以重启网关再看看。还有，如果你是新用户的话，建议先从SDKTest.java这个单元测试类看起。PermissionTest.java这个类属于基础环境完善之后，进行的高级测试。谢谢您对JDChain的关注。

**Comment by jy1989** [comment]
> 这个报错，是由于连接意外中断导致的。你可以重启网关再看看。还有，如果你是新用户的话，建议先从SDKTest.java这个单元测试类看起。PermissionTest.java这个类属于基础环境完善之后，进行的高级测试。谢谢您对JDChain的关注。

网关已经重启过很多次了  但是有commit操作也是报这个错误

另外想问一下，是不是
SDKDemo_Constant里的公私匙 == 网关gateway.conf 的keys.default的公私匙 == 四个peer中其中一个公私匙 呢？

**Comment by jy1989** [comment]
@zhaoGuangwei 

POST到 /rpc/tx的时候返回了一个0

![image](https://user-images.githubusercontent.com/1291756/68444293-69be4c00-0211-11ea-8604-d296be6c5a99.png)

**Comment by michaelmao999** [comment]
我也遇到一样的问题，网关节点的
NodeSigningAppender.process方法中发送订单返回结果为空。
AsyncFuture<byte[]> result =  messageService.sendOrdered(BinaryProtocol.encode(txMessage, TransactionRequest.class));

peer节点报错如下：
![PeerException](https://user-images.githubusercontent.com/43536056/68522456-73fe4a00-02e6-11ea-8f28-47ed14699f51.JPG)

**Comment by zhaoGuangwei** [comment]
最近有很多用户反馈这个问题，可能是操作不当导致的。我完善了一下相关文档和视频资料，大家可以参考：
1）https://github.com/blockchain-jd-com/jdchain-starter/tree/master/doc 中“从零开始部署JDChain”；
2）操作视频：https://3.cn/TDtyTS4Ze  （下载JDChain1.1.1.RELEASE版本的文件，最好同步下载字幕）

感谢您对JDChain的关注！

**Comment by jy1989** [comment]
@zhaoGuangwei 看了视频，操作应是无误的。 又重新初始化了一下账本，但还是老问题
` java.lang.IllegalStateException: Returned object not currently part of this pool`

![image](https://user-images.githubusercontent.com/1291756/68639745-85db2980-0540-11ea-9d6e-916e53ded533.png)

**Comment by zhaoGuangwei** [comment]
你查看一下，四个peer是否正常启动，看看bin中的out日志，感觉共识出了问题。
1)如果无异常，再kill掉所有的进程（类似于：ps -ef|grep 'jdchain'|grep -v grep|cut -c 9-15|xargs kill -9）
2)再重启4个peer（bin/peer-startup.sh），然后重启gw(bin/startup.sh)再试试。
3)如果仍不能解决，可启动shell中加挂debug细致分析，格式：-Dlogging.config=file:$HOME/config/log4j2.xml，log4j2.xml网上有常用格式。

**Comment by jy1989** [comment]
@zhaoGuangwei 

加上了debug 但好像没有看到有用的信息，这是我gateway的gw.out

[gw.out.zip](https://github.com/blockchain-jd-com/jdchain-starter/files/3834774/gw.out.zip)

**Comment by zhangshuang01** [comment]
您好：
        上面您说的SDKDemo_Constant里的公私匙 == 网关gateway.conf 的keys.default的公私匙 == 四个peer中其中一个公私匙， 没错，这样修改可以解决你的gateway error问题。

**Comment by zhangshuang01** [comment]
java.lang.IllegalStateException: Returned object not currently part of this pool， 这个问题是您的四个共识节点启动有失败造成的。根据我们对您问题的复现情况，应该是共识节点由于地址重用问题而没有启动成功。也就是共识节点通信用的端口已经被别的进程占用了， 所以在配置共识节点的端口前您可以通过以下两个命令检查下端口的占用情况。   lsof -i tcp:共识端口 或者netstat -anp |grep 共识端口， 如果已经被占用，共识节点再次使用该端口肯定会启动失败。

**Comment by jy1989** [comment]
> 您好：
> 上面您说的SDKDemo_Constant里的公私匙 == 网关gateway.conf 的keys.default的公私匙 == 四个peer中其中一个公私匙， 没错，这样修改可以解决你的gateway error问题。
 
谢谢，那我理解是没错误的，一直都是这样配置的。

**Comment by jy1989** [comment]
> java.lang.IllegalStateException: Returned object not currently part of this pool， 这个问题是您的四个共识节点启动有失败造成的。根据我们对您问题的复现情况，应该是共识节点由于地址重用问题而没有启动成功。也就是共识节点通信用的端口已经被别的进程占用了， 所以在配置共识节点的端口前您可以通过以下两个命令检查下端口的占用情况。 lsof -i tcp:共识端口 或者netstat -anp |grep 共识端口， 如果已经被占用，共识节点再次使用该端口肯定会启动失败。

可是我在网关上的区块链浏览器查看到的节点是正常的？   能以区块链浏览器看到的为准吗？
如果peer启动失败，网关会显示连接到peer失败的。

**Comment by jy1989** [comment]
![image](https://user-images.githubusercontent.com/1291756/68825672-eb145380-06d5-11ea-8ec0-5e75be65c9b8.png)

![image](https://user-images.githubusercontent.com/1291756/68825676-eea7da80-06d5-11ea-880b-9914367d92b9.png)

![image](https://user-images.githubusercontent.com/1291756/68825679-f2d3f800-06d5-11ea-9ad5-bc78f2253703.png)

![image](https://user-images.githubusercontent.com/1291756/68825687-f9626f80-06d5-11ea-8275-4104a910e91a.png)

![image](https://user-images.githubusercontent.com/1291756/68825716-0f703000-06d6-11ea-89d8-45d02b740201.png)

![image](https://user-images.githubusercontent.com/1291756/68826063-501c7900-06d7-11ea-890f-48843e924884.png)


![image](https://user-images.githubusercontent.com/1291756/68826051-409d3000-06d7-11ea-9510-6f17c06944fb.png)

**Comment by jy1989** [comment]
发现某些peer有错误  

![image](https://user-images.githubusercontent.com/1291756/68826695-f0739d00-06d9-11ea-98c5-e88abc1db1cc.png)

**Comment by jy1989** [comment]
换了一台电脑去做peer
还是发现同样的问题
貌似只有第一个节点没有错误信息，后面的节点都报错
`ERROR bftsmart.tom.ServiceReplica 247 init - null java.net.BindException: Address already in use`

**Comment by zhaoGuangwei** [comment]
这个就是端口冲突造成的，你首先把jdchain相关的进程全部kill掉。然后用lsof -i:端口号看看你期望使用的端口号是不是被占用了。尽量用大一点的数字。我把您这个问题在“常见问题.md”中11条做了一些说明，您参考看看，如果还有问题，直接给我微信。https://github.com/blockchain-jd-com/jdchain-starter

**Comment by zhaoGuangwei** [comment]
启动节点之前，注意修改peer/bin/peer-startup.sh中对应的端口号，如果是单机环境，记得4个端口号要不同，比如7080/7081/7082/7083等。

**Comment by zhaoGuangwei** [comment]
![image](https://user-images.githubusercontent.com/6849792/68833566-c2e51e80-06ee-11ea-87c6-3c45e1c24ca5.png)
别用6301，直接跳10个数字，用6310。

**Comment by zhaoGuangwei** [comment]
peer应用端口，指的是7080系列。共识端口（6300等）和初始化端口（22000等）步长定为10。6300/6310/6320/6330,22000/22010/22020/22030等。

**Comment by jy1989** [comment]
感谢  终于成功了，果然是端口的问题。我系统是macos，不知道有没有关系。

虽然还不知道是哪个端口的问题，但把所有端口都增大了就可以了

![image](https://user-images.githubusercontent.com/1291756/68836797-23c42500-06f6-11ea-9178-444b762874b9.png)

**Comment by klboke** [comment]
原来答案在这里，这个被关闭的issue的问题我也遇到了。定位了大半天才搞明白。 @jy1989 楼主肯定还在纳闷哪个端口冲突了。 @zhaoGuangwei 说的端口步长定为10的原因在这里：https://github.com/blockchain-jd-com/jdchain/issues/42
