### ISSUE TITLE
SDK_GateWay_Participant_Test_的使用方法

### ISSUE THREAD

**Issue by jy1989** [blockchain-jd-com/jdchain-starter#7]
看到[SDK_GateWay_Participant_Test_](https://github.com/blockchain-jd-com/jdchain-starter/blob/master/contract-starter/src/test/java/com/jd/blockchain/SDK_GateWay_Participant_Test_.java)用例，但不知道如何使用：

- 这个公私钥是新节点生成的公私钥么？

![image](https://user-images.githubusercontent.com/1291756/71225528-e7e33780-2313-11ea-83ba-ef600f0b2f39.png)

- 这个20000端口是节点管理工具的端口么？相当于8000/8001/8002/8003 ？

![image](https://user-images.githubusercontent.com/1291756/71225576-01847f00-2314-11ea-9dd6-1623752f7f2f.png)

**我理解整个流程是这样的： 先复制一个peer5文件夹，启动peer5的管理工具，然后在上面新建公私钥；修改`SDK_GateWay_Participant_Test_`指定peer5的公私钥、ip地址和管理工具端口**

但是这里使用gw地址又好像和我理解的不一样：
![image](https://user-images.githubusercontent.com/1291756/71226016-465ce580-2315-11ea-91c3-57fafb33dcce.png)

**Comment by zhaoGuangwei** [comment]
感谢您对这种高级使用的关注，20000是设置的共识端口，如果在一台机器上测试，要确保不冲突。
这是以前的一些验证过程，可以参考一下：https://3.cn/CagJrfM。如果仍有问题，可以直接给：jdchain-support@jd.com发邮件咨询。欢迎您在使用过程中提出宝贵意见！
