### ISSUE TITLE
构建4 peer时的问题：最后一个参与者，停留在“保存配置信息”直到超时。

### ISSUE THREAD

**Issue by evsward** [blockchain-jd-com/jdchain-starter#8]
题主参考了jdchain-starter使用可视工具快速构建4 peer区块链网络。

在整体配置完协调者和参与者的参数以后，先点击的协调者的“保存配置信息”，然后依次点击其他3个节点的“保存配置信息”，经过我的几次重启测试，每次最后一个点击“保存配置信息”的节点会一直pending，直到后台jump.out日志打出：
```
07:43:49.776 ERROR com.jd.blockchain.ump.util.HttpJsonClientUtils 23 httpPost - HttpPostRequestException Read timed out
07:43:49.830 ERROR com.jd.blockchain.ump.web.ExceptionResponseAdvice 31 json - Exception occurred! --[RequestURL=[POST] http://127.0.0.1:9991/peer/share][class java.lang.IllegalStateException]java.net.SocketTimeoutException: Read timed out java.lang.IllegalStateException: java.net.SocketTimeoutException: Read timed out
```
报错的同时，页面的pending消失，重新点击“保存配置信息”，会弹出java.lang.NullPointerException空指针异常。后台jump.out日志打出：
```
ERROR com.jd.blockchain.ump.web.ExceptionResponseAdvice 31 json - Exception occurred! --[RequestURL=[POST] http://127.0.0.1:9991/peer/share][class java.lang.NullPointerException]null java.lang.NullPointerException: null
```

**Comment by zhaoGuangwei** [comment]
这个你得看看是不是内存被吃光。建议修改内存为512M。jdchain-starter中“从零开始部署JDChain.md”的2.1节⑤部分。再就是主要端口是否冲突。共识端口的步长设置为10比较合适。也就是peer0的共识端口若为：6300，则peer1设置为6310。如仍有问题，可mail给：jdchain-support@jd.com进行深度剖析。感谢您对JDChain的关注。

**Comment by yuqian0218** [comment]
@evsward 今天我部署的时候遇上了同样的问题，之后仔细阅读部署文档，发现在单台节点的前提下，需要把数据库的名称做区分，如果四个节点名称有重复，你提到的问题就会复现。
