### ISSUE TITLE
根据jdchain-starter/doc/从零开始部署JDChain.md初始化账本异常

### ISSUE THREAD

**Issue by wangyinglike1234** [blockchain-jd-com/jdchain-starter#9]
您好，现在正在根据jdchain-starter/doc/从零开始部署JDChain.md文档快速部署京东区块链。
目前创建数据账本有点问题，我是在阿里云的一台服务器上进行4个peer节点的部署，保存好配置信息，点击“安装”时，有3个节点一直卡在这个步骤中
![image](https://user-images.githubusercontent.com/57782038/76732886-9fb0a580-679a-11ea-8f61-0f2b4c66adc5.png)
还有一个节点报错，异常如下：
![image](https://user-images.githubusercontent.com/57782038/76732925-bbb44700-679a-11ea-93dd-9ff4dc1149f6.png)
还有就是咨询一下，gong sjhi共识节点的端口号是有在哪个配置文件中进行配置吗？还是只要在提供的管理工具上配置就可以了啊？

**Comment by zhaoGuangwei** [comment]
你阿里云服务器的配置怎样？4个端需要进行共识，所以只要一个端出现问题，都会共识不成功。
官方的部署文档是纯手工部署的，可以修改端口，你可以看看:http://ledger.jd.com/setup.html。当时考虑到用户纯手工部署容易产生问题，所以我们启用了一个管理工具。
只要在管理工具配置就可以使用，但是如果有问题，最好把相关进程关掉，环境清理再重试。
你这个异常通常的原因是：内存不足，或者端口冲突，导致最后一个管理端不能正常启动。如果排查仍有问题，加我微信：10696699，我直接上你ECS看最省事。愉快！
